name: build_and_test_epmt

on:
  push:
  pull_request:

# thank you m. lee
# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        

    container:
      image: rockylinux:8
      env:
        POSTGRES_DB: 'EPMT'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'example'
        PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
      options: --privileged

    steps:
      - uses: actions/checkout@v4
      
      - name: test psql connection  
        run: |
          docker run --rm --network host -e PGPASSWORD=testpassword postgres:15 psql -h localhost -U testuser -d testdb -c "SELECT 1;" && break
          echo "Waiting for PostgreSQL to be ready..."
          sleep 3
          done
